### ISSUE TITLE
wrong calculation of precision

### ISSUE THREAD

**Issue by woozch** [kexinhuang12345/MolTrans#17]
Hi. 
Thank you for sharing your paper and code.
While I am looking at your code, it seems that the line that calculates precision in the evaluation step is wrong.
So I wrote this issue.

https://github.com/kexinhuang12345/MolTrans/blob/47ac16b8c158b080ba6cdaec74cd7aa9c1332b73/train.py#L79

https://en.wikipedia.org/wiki/Precision_and_recall
TPR= TP/(TP+FN) , FPR=FP/(FP+TN)
Precision=TP/(TP+FP)

**Comment by kexinhuang12345** [comment]
Hi, i see what you mean. do you want to make a PR to change it? luckily, in the paper, we are not using them as evaluation metrics.

**Comment by ypapanik** [comment]
If I am not mistaken, then this affect also the f1 score just below:
https://github.com/kexinhuang12345/MolTrans/blob/47ac16b8c158b080ba6cdaec74cd7aa9c1332b73/train.py#L81
Which means that the threshold will be wrong as well as y_pred_s:
https://github.com/kexinhuang12345/MolTrans/blob/47ac16b8c158b080ba6cdaec74cd7aa9c1332b73/train.py#L87
And that affects all the scores below. Would that mean that all the reported results must change (that might be good or bad)?

**Comment by kexinhuang12345** [comment]
Hi, it seems it should not affect the metrics. After some calculations, i find that the precision in the code = the true precision since our dataset is balanced where # neg = # pos. 

TPR = TP/(TP+FN), FPR = FP/(FP + TN)
Precision = TPR/(TPR + FPR) = TP/(TP + FP * ((TP + FN)/(FP+TN)) )

Note that (TP + FN)/(FP+TN) = # pos / # neg = 1
Thus, the precision goes back to TP/(TP + FP). 

So it should be the same. But i think this still should be fixed to avoid confusion. I would make a PR for it today.
